#############################################################################
# Makefile for building: CMSCoffee.app/Contents/MacOS/CMSCoffee
# Generated by qmake (2.01a) (Qt 4.8.4) on: Di. Aug 6 11:59:16 2013
# Project:  CMSCoffee.pro
# Template: app
# Command: /opt/local/bin/qmake -spec /opt/local/share/qt4/mkspecs/unsupported/macx-clang CONFIG+=x86_64 -o Makefile CMSCoffee.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -O2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/opt/local/share/qt4/mkspecs/unsupported/macx-clang -I. -I. -I/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/opt/local/include -F/opt/local/Library/Frameworks -F/opt/local/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -arch x86_64
LIBS          = $(SUBLIBS) -F/opt/local/Library/Frameworks -F/opt/local/lib  -F/opt/local/Library/Frameworks -F/opt/local/lib -L/opt/local/lib -framework QtXml -framework QtCore -framework QtGui 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /opt/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.8

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cmscoffeemainwindow.cpp \
		cmscoffeeusermodel.cpp \
		cmscoffeeuser.cpp \
		cmscoffeetickentry.cpp \
		cmscoffeetickmodel.cpp \
		cmscoffeeaccountentry.cpp \
		cmscoffeeaccountmodel.cpp \
		cmscoffeeusertableview.cpp \
		cmscoffeeactiveusertableview.cpp \
		cmscoffeeaccounttableview.cpp \
		cmscoffeeaccountentrywidget.cpp \
		cmscoffeeaccountentrycompletionmodel.cpp \
		cmscoffeetableviewdelegates.cpp moc_cmscoffeemainwindow.cpp \
		moc_cmscoffeeusermodel.cpp \
		moc_cmscoffeetickmodel.cpp \
		moc_cmscoffeeaccountmodel.cpp \
		moc_cmscoffeeusertableview.cpp \
		moc_cmscoffeeactiveusertableview.cpp \
		moc_cmscoffeeaccounttableview.cpp \
		moc_cmscoffeeaccountentrywidget.cpp \
		moc_cmscoffeeaccountentrycompletionmodel.cpp \
		moc_cmscoffeetableviewdelegates.cpp
OBJECTS       = main.o \
		cmscoffeemainwindow.o \
		cmscoffeeusermodel.o \
		cmscoffeeuser.o \
		cmscoffeetickentry.o \
		cmscoffeetickmodel.o \
		cmscoffeeaccountentry.o \
		cmscoffeeaccountmodel.o \
		cmscoffeeusertableview.o \
		cmscoffeeactiveusertableview.o \
		cmscoffeeaccounttableview.o \
		cmscoffeeaccountentrywidget.o \
		cmscoffeeaccountentrycompletionmodel.o \
		cmscoffeetableviewdelegates.o \
		moc_cmscoffeemainwindow.o \
		moc_cmscoffeeusermodel.o \
		moc_cmscoffeetickmodel.o \
		moc_cmscoffeeaccountmodel.o \
		moc_cmscoffeeusertableview.o \
		moc_cmscoffeeactiveusertableview.o \
		moc_cmscoffeeaccounttableview.o \
		moc_cmscoffeeaccountentrywidget.o \
		moc_cmscoffeeaccountentrycompletionmodel.o \
		moc_cmscoffeetableviewdelegates.o
DIST          = /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf \
		/opt/local/share/qt4/mkspecs/common/clang.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_cxx.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt4/mkspecs/features/mac/split_sources.prf \
		/opt/local/share/qt4/mkspecs/features/warn_on.prf \
		/opt/local/share/qt4/mkspecs/features/qt.prf \
		/opt/local/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt4/mkspecs/features/moc.prf \
		/opt/local/share/qt4/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt4/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt4/mkspecs/features/resources.prf \
		/opt/local/share/qt4/mkspecs/features/uic.prf \
		/opt/local/share/qt4/mkspecs/features/yacc.prf \
		/opt/local/share/qt4/mkspecs/features/lex.prf \
		/opt/local/share/qt4/mkspecs/features/include_source_dir.prf \
		CMSCoffee.pro
QMAKE_TARGET  = CMSCoffee
DESTDIR       = 
TARGET        = CMSCoffee.app/Contents/MacOS/CMSCoffee

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CXXFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile CMSCoffee.app/Contents/PkgInfo CMSCoffee.app/Contents/Resources/empty.lproj CMSCoffee.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) CMSCoffee.app/Contents/MacOS/ || $(MKDIR) CMSCoffee.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CMSCoffee.pro  /opt/local/share/qt4/mkspecs/unsupported/macx-clang/qmake.conf /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf \
		/opt/local/share/qt4/mkspecs/common/clang.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_cxx.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt4/mkspecs/features/mac/split_sources.prf \
		/opt/local/share/qt4/mkspecs/features/warn_on.prf \
		/opt/local/share/qt4/mkspecs/features/qt.prf \
		/opt/local/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt4/mkspecs/features/moc.prf \
		/opt/local/share/qt4/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt4/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt4/mkspecs/features/resources.prf \
		/opt/local/share/qt4/mkspecs/features/uic.prf \
		/opt/local/share/qt4/mkspecs/features/yacc.prf \
		/opt/local/share/qt4/mkspecs/features/lex.prf \
		/opt/local/share/qt4/mkspecs/features/include_source_dir.prf \
		/opt/local/Library/Frameworks/QtXml.framework/QtXml.prl \
		/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl \
		/opt/local/Library/Frameworks/QtGui.framework/QtGui.prl
	$(QMAKE) -spec /opt/local/share/qt4/mkspecs/unsupported/macx-clang CONFIG+=x86_64 -o Makefile CMSCoffee.pro
/opt/local/share/qt4/mkspecs/common/unix.conf:
/opt/local/share/qt4/mkspecs/common/mac.conf:
/opt/local/share/qt4/mkspecs/common/gcc-base.conf:
/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf:
/opt/local/share/qt4/mkspecs/common/clang.conf:
/opt/local/share/qt4/mkspecs/qconfig.pri:
/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/opt/local/share/qt4/mkspecs/features/qt_functions.prf:
/opt/local/share/qt4/mkspecs/features/qt_config.prf:
/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf:
/opt/local/share/qt4/mkspecs/features/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/release.prf:
/opt/local/share/qt4/mkspecs/features/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf:
/opt/local/share/qt4/mkspecs/features/mac/objective_cxx.prf:
/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf:
/opt/local/share/qt4/mkspecs/features/mac/split_sources.prf:
/opt/local/share/qt4/mkspecs/features/warn_on.prf:
/opt/local/share/qt4/mkspecs/features/qt.prf:
/opt/local/share/qt4/mkspecs/features/unix/thread.prf:
/opt/local/share/qt4/mkspecs/features/moc.prf:
/opt/local/share/qt4/mkspecs/features/mac/rez.prf:
/opt/local/share/qt4/mkspecs/features/mac/sdk.prf:
/opt/local/share/qt4/mkspecs/features/resources.prf:
/opt/local/share/qt4/mkspecs/features/uic.prf:
/opt/local/share/qt4/mkspecs/features/yacc.prf:
/opt/local/share/qt4/mkspecs/features/lex.prf:
/opt/local/share/qt4/mkspecs/features/include_source_dir.prf:
/opt/local/Library/Frameworks/QtXml.framework/QtXml.prl:
/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl:
/opt/local/Library/Frameworks/QtGui.framework/QtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/local/share/qt4/mkspecs/unsupported/macx-clang CONFIG+=x86_64 -o Makefile CMSCoffee.pro

CMSCoffee.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) CMSCoffee.app/Contents || $(MKDIR) CMSCoffee.app/Contents 
	@$(DEL_FILE) CMSCoffee.app/Contents/PkgInfo
	@echo "APPL????" >CMSCoffee.app/Contents/PkgInfo
CMSCoffee.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) CMSCoffee.app/Contents/Resources || $(MKDIR) CMSCoffee.app/Contents/Resources 
	@touch CMSCoffee.app/Contents/Resources/empty.lproj
	
CMSCoffee.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) CMSCoffee.app/Contents || $(MKDIR) CMSCoffee.app/Contents 
	@$(DEL_FILE) CMSCoffee.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,CMSCoffee,g" -e "s,@TYPEINFO@,????,g" /opt/local/share/qt4/mkspecs/unsupported/macx-clang/Info.plist.app >CMSCoffee.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/CMSCoffee1.0.0 || $(MKDIR) .tmp/CMSCoffee1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/CMSCoffee1.0.0/ && $(COPY_FILE) --parents cmscoffeemainwindow.h cmscoffeeusermodel.h cmscoffeeuser.h cmscoffeetickentry.h cmscoffeetickmodel.h cmscoffeeaccountentry.h cmscoffeeaccountmodel.h cmscoffeeusertableview.h cmscoffeeactiveusertableview.h cmscoffeeaccounttableview.h cmscoffeeaccountentrywidget.h cmscoffeeaccountentrycompletionmodel.h cmscoffeetableviewdelegates.h .tmp/CMSCoffee1.0.0/ && $(COPY_FILE) --parents main.cpp cmscoffeemainwindow.cpp cmscoffeeusermodel.cpp cmscoffeeuser.cpp cmscoffeetickentry.cpp cmscoffeetickmodel.cpp cmscoffeeaccountentry.cpp cmscoffeeaccountmodel.cpp cmscoffeeusertableview.cpp cmscoffeeactiveusertableview.cpp cmscoffeeaccounttableview.cpp cmscoffeeaccountentrywidget.cpp cmscoffeeaccountentrycompletionmodel.cpp cmscoffeetableviewdelegates.cpp .tmp/CMSCoffee1.0.0/ && (cd `dirname .tmp/CMSCoffee1.0.0` && $(TAR) CMSCoffee1.0.0.tar CMSCoffee1.0.0 && $(COMPRESS) CMSCoffee1.0.0.tar) && $(MOVE) `dirname .tmp/CMSCoffee1.0.0`/CMSCoffee1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CMSCoffee1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r CMSCoffee.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_cxx_make_all:
compiler_objective_cxx_clean:
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_cmscoffeemainwindow.cpp moc_cmscoffeeusermodel.cpp moc_cmscoffeetickmodel.cpp moc_cmscoffeeaccountmodel.cpp moc_cmscoffeeusertableview.cpp moc_cmscoffeeactiveusertableview.cpp moc_cmscoffeeaccounttableview.cpp moc_cmscoffeeaccountentrywidget.cpp moc_cmscoffeeaccountentrycompletionmodel.cpp moc_cmscoffeetableviewdelegates.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cmscoffeemainwindow.cpp moc_cmscoffeeusermodel.cpp moc_cmscoffeetickmodel.cpp moc_cmscoffeeaccountmodel.cpp moc_cmscoffeeusertableview.cpp moc_cmscoffeeactiveusertableview.cpp moc_cmscoffeeaccounttableview.cpp moc_cmscoffeeaccountentrywidget.cpp moc_cmscoffeeaccountentrycompletionmodel.cpp moc_cmscoffeetableviewdelegates.cpp
moc_cmscoffeemainwindow.cpp: cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeetickmodel.h \
		cmscoffeeaccountmodel.h \
		cmscoffeeaccountentrycompletionmodel.h \
		cmscoffeemainwindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ cmscoffeemainwindow.h -o moc_cmscoffeemainwindow.cpp

moc_cmscoffeeusermodel.cpp: cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeeusermodel.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ cmscoffeeusermodel.h -o moc_cmscoffeeusermodel.cpp

moc_cmscoffeetickmodel.cpp: cmscoffeetickentry.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeeaccountentry.h \
		cmscoffeetickmodel.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ cmscoffeetickmodel.h -o moc_cmscoffeetickmodel.cpp

moc_cmscoffeeaccountmodel.cpp: cmscoffeeaccountentry.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountmodel.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ cmscoffeeaccountmodel.h -o moc_cmscoffeeaccountmodel.cpp

moc_cmscoffeeusertableview.cpp: cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeeusertableview.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ cmscoffeeusertableview.h -o moc_cmscoffeeusertableview.cpp

moc_cmscoffeeactiveusertableview.cpp: cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeeactiveusertableview.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ cmscoffeeactiveusertableview.h -o moc_cmscoffeeactiveusertableview.cpp

moc_cmscoffeeaccounttableview.cpp: cmscoffeeaccountmodel.h \
		cmscoffeeaccountentry.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentrycompletionmodel.h \
		cmscoffeeaccounttableview.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ cmscoffeeaccounttableview.h -o moc_cmscoffeeaccounttableview.cpp

moc_cmscoffeeaccountentrywidget.cpp: cmscoffeeaccountmodel.h \
		cmscoffeeaccountentry.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentrycompletionmodel.h \
		cmscoffeeaccountentrywidget.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ cmscoffeeaccountentrywidget.h -o moc_cmscoffeeaccountentrywidget.cpp

moc_cmscoffeeaccountentrycompletionmodel.cpp: cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeeaccountmodel.h \
		cmscoffeeaccountentrycompletionmodel.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ cmscoffeeaccountentrycompletionmodel.h -o moc_cmscoffeeaccountentrycompletionmodel.cpp

moc_cmscoffeetableviewdelegates.cpp: cmscoffeeaccountentrycompletionmodel.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeeaccountmodel.h \
		cmscoffeetableviewdelegates.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ cmscoffeetableviewdelegates.h -o moc_cmscoffeetableviewdelegates.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp cmscoffeemainwindow.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeetickmodel.h \
		cmscoffeeaccountmodel.h \
		cmscoffeeaccountentrycompletionmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cmscoffeemainwindow.o: cmscoffeemainwindow.cpp cmscoffeeusertableview.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeeactiveusertableview.h \
		cmscoffeeaccounttableview.h \
		cmscoffeeaccountmodel.h \
		cmscoffeeaccountentrycompletionmodel.h \
		cmscoffeeaccountentrywidget.h \
		cmscoffeemainwindow.h \
		cmscoffeetickmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeemainwindow.o cmscoffeemainwindow.cpp

cmscoffeeusermodel.o: cmscoffeeusermodel.cpp cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeetickmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeeusermodel.o cmscoffeeusermodel.cpp

cmscoffeeuser.o: cmscoffeeuser.cpp cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeeuser.o cmscoffeeuser.cpp

cmscoffeetickentry.o: cmscoffeetickentry.cpp cmscoffeetickentry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeetickentry.o cmscoffeetickentry.cpp

cmscoffeetickmodel.o: cmscoffeetickmodel.cpp cmscoffeetickmodel.h \
		cmscoffeetickentry.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeeaccountentry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeetickmodel.o cmscoffeetickmodel.cpp

cmscoffeeaccountentry.o: cmscoffeeaccountentry.cpp cmscoffeeaccountentry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeeaccountentry.o cmscoffeeaccountentry.cpp

cmscoffeeaccountmodel.o: cmscoffeeaccountmodel.cpp cmscoffeeaccountmodel.h \
		cmscoffeeaccountentry.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeeaccountmodel.o cmscoffeeaccountmodel.cpp

cmscoffeeusertableview.o: cmscoffeeusertableview.cpp cmscoffeeusertableview.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeeusertableview.o cmscoffeeusertableview.cpp

cmscoffeeactiveusertableview.o: cmscoffeeactiveusertableview.cpp cmscoffeetableviewdelegates.h \
		cmscoffeeaccountentrycompletionmodel.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeeaccountmodel.h \
		cmscoffeeactiveusertableview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeeactiveusertableview.o cmscoffeeactiveusertableview.cpp

cmscoffeeaccounttableview.o: cmscoffeeaccounttableview.cpp cmscoffeetableviewdelegates.h \
		cmscoffeeaccountentrycompletionmodel.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeeaccountmodel.h \
		cmscoffeeaccounttableview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeeaccounttableview.o cmscoffeeaccounttableview.cpp

cmscoffeeaccountentrywidget.o: cmscoffeeaccountentrywidget.cpp cmscoffeeaccountentrywidget.h \
		cmscoffeeaccountmodel.h \
		cmscoffeeaccountentry.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentrycompletionmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeeaccountentrywidget.o cmscoffeeaccountentrywidget.cpp

cmscoffeeaccountentrycompletionmodel.o: cmscoffeeaccountentrycompletionmodel.cpp cmscoffeeaccountentrycompletionmodel.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeeaccountmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeeaccountentrycompletionmodel.o cmscoffeeaccountentrycompletionmodel.cpp

cmscoffeetableviewdelegates.o: cmscoffeetableviewdelegates.cpp cmscoffeetableviewdelegates.h \
		cmscoffeeaccountentrycompletionmodel.h \
		cmscoffeeusermodel.h \
		cmscoffeeuser.h \
		cmscoffeetickentry.h \
		cmscoffeeaccountentry.h \
		cmscoffeeaccountmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmscoffeetableviewdelegates.o cmscoffeetableviewdelegates.cpp

moc_cmscoffeemainwindow.o: moc_cmscoffeemainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmscoffeemainwindow.o moc_cmscoffeemainwindow.cpp

moc_cmscoffeeusermodel.o: moc_cmscoffeeusermodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmscoffeeusermodel.o moc_cmscoffeeusermodel.cpp

moc_cmscoffeetickmodel.o: moc_cmscoffeetickmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmscoffeetickmodel.o moc_cmscoffeetickmodel.cpp

moc_cmscoffeeaccountmodel.o: moc_cmscoffeeaccountmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmscoffeeaccountmodel.o moc_cmscoffeeaccountmodel.cpp

moc_cmscoffeeusertableview.o: moc_cmscoffeeusertableview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmscoffeeusertableview.o moc_cmscoffeeusertableview.cpp

moc_cmscoffeeactiveusertableview.o: moc_cmscoffeeactiveusertableview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmscoffeeactiveusertableview.o moc_cmscoffeeactiveusertableview.cpp

moc_cmscoffeeaccounttableview.o: moc_cmscoffeeaccounttableview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmscoffeeaccounttableview.o moc_cmscoffeeaccounttableview.cpp

moc_cmscoffeeaccountentrywidget.o: moc_cmscoffeeaccountentrywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmscoffeeaccountentrywidget.o moc_cmscoffeeaccountentrywidget.cpp

moc_cmscoffeeaccountentrycompletionmodel.o: moc_cmscoffeeaccountentrycompletionmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmscoffeeaccountentrycompletionmodel.o moc_cmscoffeeaccountentrycompletionmodel.cpp

moc_cmscoffeetableviewdelegates.o: moc_cmscoffeetableviewdelegates.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmscoffeetableviewdelegates.o moc_cmscoffeetableviewdelegates.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

